-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[About Xfce]====], [====[xfce4-about]====]},
{[====[Alarm Clock]====], [====[alarm-clock]====]},
{[====[Archive Manager]====], [====[file-roller]====]},
{[====[CherryTree]====], [====[cherrytree %f]====]},
{[====[File Manager]====], [====[exo-open --launch FileManager %u]====]},
{[====[Galculator]====], [====[galculator]====]},
{[====[Root Terminal]====], [====[gksu -l sakura]====]},
{[====[Sakura]====], [====[sakura]====]},
{[====[Sublime Text]====], [====[subl %F]====]},
{[====[Terminal Emulator]====], [====[exo-open --launch TerminalEmulator]====]},
{[====[UNetbootin]====], [====[/usr/bin/unetbootin]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
{[====[Dota 2]====], [====[steam steam://rungameid/570]====]}
}
applicationsmenu[40] = {
{[====[GNU Image Manipulation Program]====], [====[gimp-2.8]====]},
{[====[Image Viewer]====], [====[gpicview %f]====]}
}
applicationsmenu[50] = {
{[====[Aurora]====], [====[firefox-aurora %u]====]},
{[====[Aurora - Safe Mode]====], [====[firefox-aurora -safe-mode %u]====]},
{[====[Friends]====], [====[steam steam://open/friends]====]},
{[====[Mail Reader]====], [====[exo-open --launch MailReader %u]====]},
{[====[Skype]====], [====[env PULSE_LATENCY_MSEC=60 skype]====]},
{[====[Start Transmission Minimized]====], [====[transmission-gtk --minimized]====]},
{[====[Web Browser]====], [====[exo-open --launch WebBrowser %u]====]},
{[====[Wicd]====], [====[/usr/bin/wicd-client]====]}
}
applicationsmenu[60] = {
{[====[Adobe Reader 9]====], [====[acroread %f]====]},
{[====[Formula]====], [====[libreoffice --math]====]},
{[====[New Document]====], [====[libreoffice --writer]====]},
{[====[New Presentation]====], [====[libreoffice --impress]====]},
{[====[New Spreadsheet]====], [====[libreoffice --calc]====]}
}
applicationsmenu[70] = {
{[====[7-Zip FM]====], [====[7zFM]====]},
{[====[A Wine application]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Msi.Patch %f]====]},
{[====[A Wine application]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Windows.CompositeFont %f]====]},
{[====[A Wine application]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen VBSFile %f]====]},
{[====[Aurora]====], [====[/opt/firefox-aurora/firefox %u]====]},
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[Bulk Rename]====], [====[/usr/lib/Thunar/ThunarBulkRename %F]====]},
{[====[Create Launcher on the panel]====], [====[xfce4-panel --add=launcher %u]====]},
{[====[HDSPConf]====], [====[hdspconf]====]},
{[====[HDSPMixer]====], [====[hdspmixer]====]},
{[====[hh]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen chm.file %f]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[make]====], [====[make %f]====]},
{[====[notepad]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen inifile %f]====]},
{[====[notepad]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen txtfile %f]====]},
{[====[Notification Daemon]====], [====[/usr/lib/notification-daemon-1.0/notification-daemon]====]},
{[====[Openbox]====], [====[openbox]====]},
{[====[Orage Calendar]====], [====[orage]====]},
{[====[Orage Globaltime]====], [====[globaltime]====]},
{[====[Orage preferences]====], [====[orage -p]====]},
{[====[Privilege granting]====], [====[gksu-properties]====]},
{[====[QXKB]====], [====[qxkb]====]},
{[====[Removable Drives and Media]====], [====[thunar-volman-settings]====]},
{[====[rundll32]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Application.Manifest %f]====]},
{[====[rundll32]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Application.Reference %f]====]},
{[====[rundll32]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen InternetShortcut %f]====]},
{[====[Windows Presentation Foundation Host]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Windows.Xbap %f]====]},
{[====[Windows Presentation Foundation Host]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen Windows.XamlDocument %f]====]},
{[====[Wine Internet Explorer]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen pngfile %f]====]},
{[====[Wine Internet Explorer]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen jpegfile %f]====]},
{[====[Wine Internet Explorer]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen giffile %f]====]},
{[====[Wine Internet Explorer]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen pjpegfile %f]====]},
{[====[Wine Windows Program Loader]====], [====[wine start /unix %f]====]},
{[====[winebrowser]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen xmlfile %f]====]},
{[====[winebrowser]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen htmlfile %f]====]},
{[====[winebrowser]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen htmlfile %f]====]},
{[====[winhlp32]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen hlpfile %f]====]},
{[====[wordpad]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen wrifile %f]====]},
{[====[wordpad]====], [====[env WINEPREFIX="/home/master-p/.wine" wine start /ProgIDOpen rtffile %f]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[Netbeans]====], [====[netbeans]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]},
{[====[Qt4 QDbusViewer]====], [====[qdbusviewer-qt4]====]}
}
applicationsmenu[90] = {
{[====[AcetoneISO]====], [====[acetoneiso %f]====]},
{[====[MPlayer Media Player]====], [====[mplayer %F]====]},
{[====[Prev]====], [====[deadbeef --prev]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc --started-from-file]====]},
{[====[webcam test Utility]====], [====[qv4l2]====]}
}
applicationsmenu[100] = {
{[====[Batti]====], [====[batti]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[GParted]====], [====[/usr/bin/gparted_polkit %f]====]},
{[====[Guake Terminal]====], [====[guake]====]},
{[====[Open Folder with Thunar]====], [====[thunar %F]====]},
{[====[Oracle VM VirtualBox]====], [====[VirtualBox]====]},
{[====[Thunar File Manager]====], [====[thunar %F]====]},
{[====[Usbview]====], [====[usbview]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[Customize Look and Feel]====], [====[lxappearance]====]},
{[====[File Manager]====], [====[thunar-settings]====]},
{[====[Guake Preferences]====], [====[guake-prefs]====]},
{[====[NVIDIA X Server Settings]====], [====[/usr/bin/nvidia-settings]====]},
{[====[Openbox Configuration Manager]====], [====[obconf %f]====]},
{[====[Panel]====], [====[xfce4-panel --preferences]====]},
{[====[Preferred Applications]====], [====[exo-preferred-applications]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]},
{[====[Window Manager]====], [====[xfwm4-settings]====]},
{[====[Window Manager Tweaks]====], [====[xfwm4-tweaks-settings]====]},
{[====[Workspaces]====], [====[xfwm4-workspace-settings]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end