 local menubeceed89e397495003f6ff5a4d895d66 = {
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"HDSPConf", "hdspconf", "/usr/share/pixmaps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/pixmaps/hdspmixer.png" },
     {"Kamerka", "kamerka", "/usr/share/pixmaps/kamerka.png" },
     {"OpenShot Video Editor", "openshot ", "/usr/share/pixmaps/openshot.svg" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Shotcut", "shotcut-bin", "/usr/share/pixmaps/shotcut.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png" },
     {"Sonata", "sonata", "/usr/share/pixmaps/sonata.png" },
     {"samowar", "/usr/bin/samowar", "///usr/share/samowar/icons/samowar.png" },
     {"uTox", "utox", "/usr/share/icons/hicolor/16x16/apps/utox.png" },
     {"Медиаплеер VLC", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Регулятор громкости PulseAudio", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
 }

 local menu9a1dcda9efe2bfc3963e75f98cc1ffd5 = {
     {"DraftSight", "\"/opt/dassault-systemes/DraftSight/Linux/DraftSight\""},
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Rawstudio", "rawstudio ", "/usr/share/icons/rawstudio.png" },
     {"XnView Retro", "/opt/XnRetro/XnRetro", "/usr/share/pixmaps/xnretro.png" },
     {"mtPaint", "mtpaint ", "/usr/share/pixmaps/mtpaint.png" },
     {"Просмотр документов", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Просмотр изображений", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
 }

 local menu9450b445fe92072aefd60520dcc39900 = {
     {"Anomaly Warzone Earth", "\"/home/master-p/AnomalyWarzoneEarth/AnomalyWarzoneEarth\"", "///home/master-p/AnomalyWarzoneEarth/icon.png" },
     {"Dota 2", "steam steam://rungameid/570", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Everlasting Summer", "steam steam://rungameid/331470"},
     {"Left 4 Dead 2", "steam steam://rungameid/550", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Teeworlds", "teeworlds", "/usr/share/pixmaps/teeworlds.png" },
 }

 local menu25385e702800d748c19cf6ea4f5811ec = {
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Cutegram", "cutegram", "/usr/share/icons/hicolor/16x16/apps/cutegram.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"EiskaltDC++ Qt", "eiskaltdcpp-qt "},
     {"Everpad", "everpad ", "/usr/share/icons/hicolor/128x128/apps/everpad.png" },
     {"GNOME PPP", "gnome-ppp", "/usr/share/icons/hicolor/48x48/apps/gnome-ppp.png" },
     {"Gajim", "gajim", "/usr/share/icons/hicolor/64x64/apps/gajim.png" },
     {"Haguichi", "haguichi", "/usr/share/icons/hicolor/16x16/apps/haguichi.png" },
     {"Insync", "insync start"},
     {"LinuxDC++", "linuxdcpp", "/usr/share/icons/hicolor/16x16/apps/linuxdcpp.png" },
     {"Midori (приватный режим)", "midori --private ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Mumble", "mumble "},
     {"Pale Moon Web Browser", "palemoon ", "/usr/share/icons/hicolor/16x16/apps/palemoon.png" },
     {"Remmina", "remmina", "/usr/share/icons/hicolor/16x16/apps/remmina.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"SpiderOak", "SpiderOak", "/usr/share/pixmaps/SpiderOak.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamSpeak 3", "teamspeak3"},
     {"Tor-Browser (ru)", "/usr/bin/tor-browser-ru", "///usr/share/pixmaps/tor-browser-ru.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"VMware View Client", "vmware-view", "/usr/share/icons/hicolor/48x48/apps/vmware-view.png" },
     {"Viber", "viber", "/usr/share/icons/hicolor/16x16/apps/viber.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"uTox", "utox", "/usr/share/icons/hicolor/16x16/apps/utox.png" },
     {"wpa_gui", "wpa_gui", "/usr/share/pixmaps/wpa_gui.svg" },
     {"Интернет", "midori ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Навигатор Avahi по серверам SSH", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Навигатор Avahi по серверам VNC", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Удаленный просмотр", "remote-viewer ", "/usr/share/icons/hicolor/16x16/apps/virt-viewer.png" },
 }

 local menud26c1170c5110a4264a8a8a89ec20529 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Математический инструмент Genius", "gnome-genius ", "/usr/share/icons/hicolor/16x16/apps/gnome-genius.png" },
 }

 local menu8caf0567988f6898bf53e8c848c6f7bc = {
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Master PDF Editor", "/opt/masterpdfeditor/masterpdfeditor3 ", "/usr/share/pixmaps/pdfeditor.png" },
     {"Просмотр документов", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

 local menu8b25bc71fce7a929a6124e9354c07cdb = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"CLion EAP", "\"/usr/bin/clion-eap\" ", "/usr/share/pixmaps/clion-eap.svg" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"MonoDevelop", "monodevelop ", "/usr/share/icons/hicolor/16x16/apps/monodevelop.png" },
     {"Ninja IDE", "ninja-ide", "/usr/share/pixmaps/ninja-ide.png" },
     {"OpenJDK 1.7.0 Monitoring & Management Console", "_BINDIR_/jconsole"},
     {"OpenJDK 1.7.0 Policy Tool", "_BINDIR_/policytool"},
     {"PyCharm", "/usr/bin/pycharm", "/usr/share/pixmaps/pycharm.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "qtcreator ", "/usr/share/icons/hicolor/16x16/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
 }

 local menu13155df48f218a078bb8bdc9649e5b20 = {
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Guake Terminal", "guake", "/usr/share/icons/hicolor/16x16/apps/guake.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"VMware View Client", "vmware-view", "/usr/share/icons/hicolor/48x48/apps/vmware-view.png" },
     {"WinUSB", "winusbgui", "/usr/share/pixmaps/winusbgui-icon.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvtdaemon", "urxvtd -ofq", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Менеджер виртуальных машин", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"Обозреватель Avahi Zeroconf", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Редактор конфигурации", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Файловый менеджер PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
 }

 local menu91af6ed4e0be6a48ab48ec8b6e768568 = {
     {"Caffeine", "/usr/bin/caffeine", "/usr/share/icons/hicolor/16x16/apps/caffeine.png" },
     {"CoverGloobus", "covergloobus", "///usr/share/covergloobus/images/covergloobus.png" },
     {"Double Commander", "doublecmd", "/usr/share/pixmaps/doublecmd.png" },
     {"KeePassX", "keepassx ", "/usr/share/pixmaps/keepassx.xpm" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"SpiderOak", "SpiderOak", "/usr/share/pixmaps/SpiderOak.png" },
     {"Sublime Text", "subl ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Диски", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Математический инструмент Genius", "gnome-genius ", "/usr/share/icons/hicolor/16x16/apps/gnome-genius.png" },
     {"Менеджер архивов", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"Терминал", "exo-open --launch TerminalEmulator", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Улучшенный VI", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
 }

xdgmenu = {
    {"Аудио и видео", menubeceed89e397495003f6ff5a4d895d66},
    {"Графика", menu9a1dcda9efe2bfc3963e75f98cc1ffd5},
    {"Игры", menu9450b445fe92072aefd60520dcc39900},
    {"Интернет", menu25385e702800d748c19cf6ea4f5811ec},
    {"Образовательные", menud26c1170c5110a4264a8a8a89ec20529},
    {"Офис", menu8caf0567988f6898bf53e8c848c6f7bc},
    {"Программирование", menu8b25bc71fce7a929a6124e9354c07cdb},
    {"Системные", menu13155df48f218a078bb8bdc9649e5b20},
    {"Стандартные", menu91af6ed4e0be6a48ab48ec8b6e768568},
}

